# Generated by Django 2.1.1 on 2018-09-24 08:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('first_follow_up', models.CharField(blank=True, max_length=100)),
                ('second_follow_up', models.CharField(blank=True, max_length=100)),
                ('third_follow_up', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('reference', models.CharField(choices=[('a', 1), ('b', 2), ('c', 3)], max_length=100)),
                ('status', models.CharField(choices=[('a', 1), ('b', 2), ('c', 3)], max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('courses', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiry.Enquiry'),
        ),
    ]
