# Generated by Django 2.1.1 on 2018-09-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_auto_20180924_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='enquiry',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='first_follow_up',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='remark',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='second_follow_up',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='third_follow_up',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
