# Generated by Django 2.1.1 on 2018-09-25 18:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0005_auto_20180925_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date(2018, 9, 25))),
                ('remark', models.CharField(max_length=100)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquries', to='enquiry.Course')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquries', to='enquiry.References')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquries', to='enquiry.Status')),
            ],
        ),
    ]
