# Generated by Django 2.1.1 on 2018-09-25 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0006_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
