# Generated by Django 2.1.1 on 2018-09-25 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0007_auto_20180925_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.TimeField()),
                ('scheduled_date', models.DateField()),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('remarks', models.TextField()),
                ('enquiry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='enquiry.Enquiry')),
            ],
        ),
    ]
