# Generated by Django 2.1.1 on 2018-09-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0008_followup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='references',
            options={},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={},
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='courses',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
