# Generated by Django 2.1.1 on 2018-09-26 16:50

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0011_auto_20180926_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/static/media/course_content'), upload_to=''),
        ),
    ]
