# Generated by Django 2.1.1 on 2018-09-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0014_auto_20180929_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='enquries', to='enquiry.Course'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
