# Generated by Django 2.1.1 on 2018-10-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0019_auto_20181001_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='possibility',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
