# Generated by Django 2.1.1 on 2018-10-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0020_status_possibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='possibility',
        ),
    ]
