# Generated by Django 2.1.1 on 2018-10-01 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0021_remove_status_possibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Possibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possibility', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='enquiry',
            name='possibility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enquries', to='enquiry.Possibility'),
            preserve_default=False,
        ),
    ]
