# Generated by Django 2.1.1 on 2018-10-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0022_auto_20181001_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='remark',
            new_name='comment',
        ),
    ]
