# Generated by Django 2.1.1 on 2018-10-02 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0023_auto_20181001_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='possibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquries', to='enquiry.Possibility'),
        ),
    ]
